services:
  chat-app-1:
    build: .
    ports:
      - "5000:5000"
    network_mode: "host"
    command: ["python", "app.py", "--port", "5000"]

  chat-app-2:
    build: .
    ports:
      - "5001:5001"
    network_mode: "host"
    command: ["python", "app.py", "--port", "5001"]
